# vim:set ft=tmux:

set -g @thm_strong_primary "#c5a96e"
set -g @thm_primary "#c5a96e"
set -g @thm_light_primary "#ddc999"
set -g @thm_secondary "#a3b87a"
set -g @thm_prefix "#ddc999"
set -g @thm_fg "#ddc999"

set -g @thm_core "#121210"
set -g @thm_mantle "#1b2a1e"
set -g @thm_surface "#243b28"
set -g @thm_visual "#3a4c38"

set -g @thm_red "#b85a38"
set -g @thm_orange "#9b672a"
set -g @thm_yellow "#c5a96e"
set -g @thm_green "#6a8c3e"
set -g @thm_teal "#a3b87a"
set -g @thm_blue "#8c7a6b"
set -g @thm_indigo "#a18d5b"

set -gF message-style "fg=#{@thm_primary},bg=#{@thm_mantle},align=centre"
set -gF message-command-style "fg=#{@thm_secondary},bg=#{@thm_mantle},align=centre"
set -gF mode-style "bg=#{@thm_visual},fg=#{@thm_fg},bold"
set -gF clock-mode-colour "#{@thm_primary}"

%if "#{>=:#{version},3.4}"
  set -gF menu-selected-style "fg=#{@thm_fg},bold,bg=#{@thm_surface}"
  set -gF popup-style "bg=#{@thm_core},fg=#{@thm_fg}"
  set -gF popup-border-style "fg=#{@thm_surface}"
%endif

setw -gF pane-active-border-style "bg=#{@thm_mantle},fg=#{@thm_primary}"
setw -gF pane-border-style "bg=#{@thm_mantle},fg=#{@thm_surface}"
set -gF status-style "bg=#{@thm_mantle},fg=#{@thm_secondary}"
set -gF window-status-last-style "bg=#{@thm_mantle},fg=#{@thm_strong_primary}"
set -gF window-status-activity-style "bg=#{@thm_strong_primary},fg=#{@thm_core}"
set -gF window-status-bell-style "bg=#{@thm_strong_primary},fg=#{@thm_core},bold"
